#!/usr/bin/env bash
set -e

echo "==========================="
echo "generate sources"
cd crates/gravity/
lisi -o /dev/null ../../docs/gravity.adoc
lisi -o /dev/null ../../docs/query_language.adoc
lisi -o /dev/null ../../docs/schema.adoc
cd ../..
cd crates/backend_filestore/
lisi -o /dev/null ../../docs/backends_filestore.adoc
cd ../..

echo "==========================="
echo "build and test"
cargo test

