#!/usr/bin/env bash
set -e

echo "==========================="
echo "check for modifications"
./scripts/check_file_changes.ts || should_generate_sources=$?

if [[ $should_generate_sources -eq 0 ]]; then
  echo "==========================="
  echo "generate sources"
  cd crates/gravity/
  lisi -o /dev/null ../../docs/gravity.adoc
  lisi -o /dev/null ../../docs/query_language.adoc
  lisi -o /dev/null ../../docs/schema.adoc
  lisi -o /dev/null ../../docs/key_value_store.adoc
  cd ../..
  cd crates/backend_filestore/
  lisi -o /dev/null ../../docs/backends_filestore.adoc
  cd ../..
fi

echo "==========================="
echo "build and test"
cargo test

